#!/bin/sh

# Copyright (c) 2019, Felix Jian
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

read_n() {
    STTY=$(stty -g)
    WAIT=$(($1*10))
    stty -icanon min 0 time $WAIT ignbrk -brkint -ixon isig
    read KEY
    stty "$STTY"
}

mkdir ~/.cache > /dev/null
OUT=~/.cache/cowquotes

stty -echo
echo > "$OUT" &&
    while true; do
        for i in $(cowsay -l | tail +2); do
            printf "\033c"
            fortune | tee -a "$OUT" | cowsay -f "$i" | sed "$ s/$/\n\n\ncowfile: $i/" | lolcat
            echo "----"  >> "$OUT"
            read_n 15
        done
    done

