#!/bin/sh

read_n() {
    STTY=$(stty -g)
    WAIT=$(($1*10))
    read KEY
    stty "$STTY"
}

mkdir ~/.cache > /dev/null
OUT=~/.cache/cowquotes

stty -echo
echo > "$OUT" &&
    while true; do
        for i in $(cowsay -l | tail +2); do
            printf "\033c"
            fortune -o | tee -a "$OUT" | 
                cowsay -f "$i" | sed "$ s/$/\n\n\ncowfile: $i/" | 
                lolcat
            echo "----"  >> "$OUT"
            read_n 15
        done
    done

