#!/bin/sh

read_n() {
	stty=$(stty -g)
	wait=$(($1 * 10))
	stty -icanon min 0 time $wait ignbrk -brkint -ixon isig
	read -r _
	stty "$stty"
}

cache_dir=${XDG_CACHE_HOME:-$HOME/.cache}/quoteslides
mkdir -p "$cache_dir"
outfile=$cache_dir/quotes.txt

stty -echo
echo >"$outfile" &&
	while true; do
		for i in $(cowsay -l | tail +2); do
			printf "\033c"
			fortune | tee -a "$outfile" |
				cowsay -f "$i" | sed "$ s/$/\n\n\ncowfile: $i/" |
				lolcat
			echo "----" >>"$outfile"
			read_n 15
		done
	done
